spring:
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: puni_db
  application:
    name: userservice

  kafka:
    bootstrap-servers: host.docker.internal:9092
eureka:
  client:
    service-url:
      defalutZone: http://host.docker.internal:8761/eureka/

server:
  port: 9898

